# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0006_auto_20160917_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='last_error_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='source',
            name='last_time_crawled',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 23, 18, 51, 33, 791611, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
