# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0010_auto_20160923_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allurl',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
